set(OPTFLAGS "${OPTFLAGS} -O3")

set(CMAKE_C_FLAGS_RELEASE "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

# Added by LittleLaGi
set(TEST_SUITE_BENCHMARKING_ONLY "ON" CACHE STRING "")
set(TEST_SUITE_USE_PERF "ON" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt" CACHE STRING "")

